Openai text summarizer
triggerdotdev/examples pull request #1
Opened 2023-07-20 09:56 UTC by samejr

2023-07-20 18:06 UTC, matt-aitken requested changes
A few really small changes. This is really good.

2023-07-20 18:06 UTC, matt-aitken commented on openai-text-summarizer/README.md
You need to add a Trigger.dev Readme like the other ones here?

2023-07-20 18:06 UTC, matt-aitken commented on openai-text-summarizer/src/app/Form.tsx
> +  const [isLoading, setHasSumbitted] = useState(false);
Usually it would be the same on the left and right, e.g.
`isLoading, setIsLoading`

2023-07-20 18:06 UTC, matt-aitken commented on openai-text-summarizer/src/app/Form.tsx
> +    setHasSumbitted(true);
There's a typo in this everywhere

2023-07-20 18:06 UTC, matt-aitken commented on openai-text-summarizer/src/app/Form.tsx
> +            <Button disabled={text === "" ? true : false}>
```suggestion
            <Button disabled={text === ""}>
```
You don't need the true or false here. `text === ""` will return `true` or `false`

2023-07-20 18:06 UTC, matt-aitken commented on openai-text-summarizer/src/jobs/textSummarizer.ts
> +  logLevel: "debug",
I'd probably remove the `logLevel`

2023-07-21 09:15 UTC, samejr commented
@matt-aitken all the fixes should be in and includes a new .md file

2023-08-02 16:59 UTC, closed without merging